import XCTest
@testable import spm_cxx_interop_autogenerated_entrypoint

final class spm_cxx_interop_autogenerated_entrypointTests: XCTestCase {
    func testExample() throws {
        // XCTest Documentation
        // https://developer.apple.com/documentation/xctest

        // Defining Test Cases and Test Methods
        // https://developer.apple.com/documentation/xctest/defining_test_cases_and_test_methods
    }
}
